services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: formrank-dev
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    command: npm run dev
    volumes:
      - .:/opt/app
      - /opt/app/node_modules